displayName=Scavenger
author=Guobmin
description=Find the nearest free pickup location for common F2P items
tags=items,f2p,navigation,minimap
version=1.2
plugins=com.scavenger.ScavengerPlugin
build=standard
